[package]
name = "cpu-burn-test"
version = "0.1.0"
edition = "2021"

[dependencies]
burn-ndarray = { path = "crates/burn-ndarray" }
burn-tensor = { path = "crates/burn-tensor" }

[[bin]]
name = "cpu-burn-test" 
path = "cpu_burn_test.rs"
