[package]
name = "wgpu-direct-video"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { path = "../../crates/burn", features = ["wgpu"] }

[[bin]]
name = "basic_tensor_stream"
path = "src/basic_tensor_stream.rs"

[[example]]
name = "minimal_working"
path = "examples/minimal_working.rs"
